### ISSUE TITLE
Font and Twitter Feed Module

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/election-nepal#11]
The whole font looks pretty odd, can we use another and "Recent Data" is written at Twitter Feed Module. Can we incorporate more than one hashtag? #LocalElection #NepalVotes and others?

**Comment by sagargg** [comment]
yeah..   we can include more than one hashtag.  what are the  possible popular  hashtag.

**Comment by nikeshbalami** [comment]
#LocalElection, #NepalVotes, #ElectionNepal and #Youth4Election. Replace the Recent Data with Twitter Feed.
