### ISSUE TITLE
No download link update at Datasets module

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/election-nepal#16]
Update and redirect all the Datasets at Github repo for download. Currently it's only updated at Homepage, not inside Datasets menu.

**Comment by nikeshbalami** [comment]
This isn't solved yet, still not redirected at GitHub repo

**Comment by studenton** [comment]
As far as I understand, the pages like Datasets and all are created dynamically, similar to WordPress? And these have been deployed to the production site but not modifiable from this GitHub repo. @sagargg . 

So I'm not able to modify it @nikeshbalami

**Comment by sagargg** [comment]
I did not understand  the  issue about.  Now it suppose to work please check is it working or not.??

**Comment by nikeshbalami** [comment]
Yeah its working now 👍
