### ISSUE TITLE
Use topojson instead of geojson

### ISSUE THREAD

**Issue by mesaugat** [okfnepal/election-nepal#17]
Loading a 2.3 MB GeoJSON data is too slow and is not good for slow internet connections. For faster load times try using [topojson](https://github.com/topojson/topojson) instead. 

I have a topojson for Nepal here: https://github.com/mesaugat/geoJSON-Nepal/blob/master/nepal-districts.topojson

It's only 237 KB. To use topojson with leaflet you'll have to include [topojson.v1.min.js](http://d3js.org/topojson.v1.min.js) in your script.

**Comment by nikeshbalami** [comment]
This is a great idea, thanks for suggestion Saugat. Assigning someone for this :)

**Comment by sagargg** [comment]
@mesaugat  Thanks  for suggestion  and also providing us topojson data.
