### ISSUE TITLE
Disable zooming and panning 

### ISSUE THREAD

**Issue by mesaugat** [okfnepal/election-nepal#18]
* There's no need to zoom in and out of the map. Similarly, we don't need to move the map too.
* Also, use some map tiles/layers from [Mapbox](https://www.mapbox.com/) so that the background doesn't look empty. (The free tier should work fine)
* This could be another alternative to Mapbox: http://leaflet-extras.github.io/leaflet-providers/preview/#filter=HERE

**Comment by nikeshbalami** [comment]
Guys what do you say @studenton and @sagargg, sounds good for me. We can ask more help on this from @mesaugat if we get stuck in between.

**Comment by nikeshbalami** [comment]
This is a nice idea, I am up for it. Do you guys know how to do it @sagargg and @studenton. This can be helpful to make site mobile friendly.
