### ISSUE TITLE
Any one  interested to give style on  Page sidebar.

### ISSUE THREAD

**Issue by sagargg** [okfnepal/election-nepal#22]

**Comment by msucil** [comment]
I think I'm going to give a try. Since I've not done anything in python before and if everything goes well while setting up the project then I'm in.

**Comment by nikeshbalami** [comment]
Great Sushil, Jump in 👍

**Comment by msucil** [comment]
@sagargg which tool are you using for converting sass to css in this project?

**Comment by sagargg** [comment]
If you're using a distribution of Linux, you'll need to install [Ruby ](https://www.ruby-lang.org/en/documentation/installation/) first.  
`sudo su -c "gem install sass"`
try this one [http://koala-app.com](http://koala-app.com).

**Comment by sagargg** [comment]
Good work @msucil..
