### ISSUE TITLE
Compare Candidates

### ISSUE THREAD

**Issue by amitness** [okfnepal/election-nepal#26]
Are the plans and policies of nominated candidates shared publicly?

If so, we could create a prototype of a tool that allows comparing two candidates for a position based on several factors such as their age, education level, achievements, affiliated party, their policies on [X, X, X], views on X, Y, Z.?

If I'm not sure whom to vote, this tool can help me take decision based on the factual data rather than on basis of what others suggest.

It could be a part of this project or spin off as a separate tool.

**Comment by nikeshbalami** [comment]
Great Idea!! ECN don't shares those but local news media shares it, we can college those data. Lets choose some key indicator and we need to do this for key districts and major position like, KTM districts and Mayor position, same for others. What say??

**Comment by studenton** [comment]
Yes, let's start with only Mayor position for Kathmandu. It's in hype as well and can be doable for the MVP. Once that's setup, it'll be easy to extend it to anything else. 

Btw, I'll still be inactive for one more week. 2 more exams to go :smile: .

**Comment by nikeshbalami** [comment]
haha sure take your time, we can start doing it once your exams finished. I will keep on eyes on different data resources.

**Comment by nikeshbalami** [comment]
@studenton Lets start this

**Comment by studenton** [comment]
Give me 2 more days. Last exam on Apr. 26. I'll be active from 27 onwards.

**Comment by rackeranjani** [comment]
Region: 
Province 3: Kageshwori Manohara Oda: 6 @kshitizkhanal7 
Province 3: KTM: Mayor and upmayor @nikeshbalami 
Province 3: KTM: oda: 32 Firoz
Lamjung: Sushil (besisahar Nagarpalika)

Attributes:

Age
Education
Promise
Occupation
achievements
affiliated party
their policies on [X, X, X], views on X, Y, Z

**Comment by amitness** [comment]
I researched on existing templates / projects that we could adapt but didn't find any. Btw, found this on social media.

![](https://scontent.fktm3-1.fna.fbcdn.net/v/t1.0-9/18268608_10212809650941987_7178984741023811292_n.jpg?oh=569bb19b7500c0bfe30020105d1f00a8&oe=59BC284A)
