### ISSUE TITLE
Enable gzip compression

### ISSUE THREAD

**Issue by studenton** [okfnepal/election-nepal#38]
Google PageSpeed insights gives a very low ranking 38 for the site: [PageSpeed Results](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Felectionnepal.org&tab=mobile)

It is suggesting to enable gzip compression for these files. 

Compressing http://electionnepal.org/…ts/javascripts/nepal-districts.topo.json could save 189.1KiB (79% reduction).
Compressing http://electionnepal.org/static/assets/stylesheets/style.css could save 128KiB (84% reduction).
Compressing http://electionnepal.org/static/assets/javascripts/leaflet.js could save 96KiB (73% reduction).
Compressing http://electionnepal.org/static/assets/stylesheets/leaflet.css could save 8.5KiB (76% reduction).
Compressing http://electionnepal.org/static/assets/javascripts/common.js could save 5.2KiB (75% reduction).

@sagargg I researched and it's suggested on internet to enable gzip from server configuration rather than from Django, if server supports it.

**Comment by sagargg** [comment]
yeah! now server is setup with mime gzip compressor.

**Comment by studenton** [comment]
Cool. Score increased by 12.
