### ISSUE TITLE
Dataset preview not compatible for big dataset

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/election-nepal#42]
Dataset preview is not compatible for big datasets, how about removing "Both Recent" from sidebar while previewing. 

![screen shot 2017-04-25 at 8 11 57 pm](https://cloud.githubusercontent.com/assets/3656268/25390827/59e0a1ae-29f4-11e7-8c44-932f3c65b2b2.png)

**Comment by sagargg** [comment]
I'm trying to add  horizontal scroll features for such data. I'm trying to figure it out.

**Comment by nikeshbalami** [comment]
Yay Yay this it great now :) :1st_place_medal:
