### ISSUE TITLE
Adding list of candidates.

### ISSUE THREAD

**Issue by shubhajeet** [okfnepal/election-nepal#48]
I want to point out to this news post. [http://www.onlinekhabar.com/2017/05/579117/](http://www.onlinekhabar.com/2017/05/579117/) containing the list of candidates.

I was unable to find the list of candidates from the official source but we should keep this data. It may be helpful if we want to create polls.

Also if we can we should enquire election commission for detail candidate list and information including those candidates from ward. 

> I have no idea who has stood up as ward members they would take crucial role of minister of local goverment and media is not giving them space.

**Comment by shubhajeet** [comment]
Help in converting this to spreadsheet or json format. 

> Can we just ask the election comission for data through email?

pradesh 3: 
https://docs.google.com/spreadsheets/d/1qbeuaOkK8nD4FX0DgJ9Z8RKVpuSzXIBXuCyUXYTLayo/preview/sheet?gid=1792251288
pradesh 4
https://docs.google.com/spreadsheets/d/1qbeuaOkK8nD4FX0DgJ9Z8RKVpuSzXIBXuCyUXYTLayopr/preview/sheet?gid=1462653766
pradesh 6: 
https://docs.google.com/spreadsheets/d/1qbeuaOkK8nD4FX0DgJ9Z8RKVpuSzXIBXuCyUXYTLayo/preview/sheet?gid=1498314332

**Comment by shubhajeet** [comment]
Ok here is my best effort on conversion ko excel sheet.
https://docs.google.com/spreadsheets/d/1D6ftX_sVB69gtaYNV1RRw5QcBuV4KYCgACwkPhYenCs/edit?usp=sharing
which if converted to csv will look like
https://gist.github.com/shubhajeet/5185214a2a9e42263450a9eb636a4a06

**Comment by nikeshbalami** [comment]
Hey @shubhajeet, Nirmal was working on its scrapping but you were super fast. Thank man, It would be awesome if you can Pull Request this Data at https://github.com/okfnepal/election-nepal-data by giving it suitable name. Since, this is the great effort and would be awesome to have it under you name :)

**Comment by shubhajeet** [comment]
@nikeshbalami 
Can I push?
Also how do you link that with website?

**Comment by nikeshbalami** [comment]
Great, Once you pushed it, I will update it into the portal. The Datasets which are in the portal are directly linked with GitHub raw file and It would be better if we can make three separate files for all three Pradesh so that user will find easy to access it.

**Comment by shubhajeet** [comment]
There is some empty records and may be the serial number is redundant. If this will be the issue on site we can use google sheets to remove the record.

**Comment by nikeshbalami** [comment]
For now its okay, Later we can make correction of this errors by comparing it, lets wait I think Election Commission will publish the final list by tomorrow.

**Comment by shubhajeet** [comment]
Great
