### ISSUE TITLE
Displaying json data of current result

### ISSUE THREAD

**Issue by shubhajeet** [okfnepal/election-nepal#55]
I have scrapped the election result from the election.comission website but it is in json so we may have to convert it into csv to display on the site.

**Comment by nikeshbalami** [comment]
Thank you so much @shubhajeet, My plan is to wait until the final result it published. What do you say :)

**Comment by shubhajeet** [comment]
I think all the result of gaupalika is out and it looks like it will take time to count of Mahanagar. We may replace it at the end and just show the current result on the site for anybody interested to analyze.
