### ISSUE TITLE
Add instructions to start local development

### ISSUE THREAD

**Issue by studenton** [okfnepal/election-nepal#7]
There is a fabfile and requirements.txt. I see certain environment variables are also being used. Need instructions on how to setup it locally.

**Comment by studenton** [comment]
@sagargg

**Comment by sagargg** [comment]
@studenton  fabfile is only needed while  deploying.  It is a django project. Do same as django. Create Python virtual environment. install all the dependencies from requirements.txt and   If you not familiar with django do following steps. 
`python manage.py makemigrations`
`python manage.py migrate`
`python manage.py runserver`

**Comment by studenton** [comment]
@sagargg Worked. Thanks a lot. I'll add this instructions to the README.
