### ISSUE TITLE
Update link to datasets in Recent Data with GitHub datasets links

### ISSUE THREAD

**Issue by studenton** [okfnepal/election-nepal#9]
Currently, the datasets under **Recent Data** section in hosted on the site itself. We could link the datasets to the the CSV in GitHub repo.

Example:

Replace 
```
http://electionnepal.org/static/media/uploads/Data/total_number_of_registered_political_parties_per_districts.csv
```
with

```
https://raw.githubusercontent.com/okfnepal/election-nepal-data/master/Total%20number%20of%20registered%20political%20parties%20per%20districts.csv
```

That way, we can update the datasets on GitHub itself and the change is posted. We don't need to crossupdate both on the site and on GitHub twice.

**Comment by studenton** [comment]
@sagargg You're more familiar with how the site fetches and visualizes the datasets. Can this be done?

**Comment by sagargg** [comment]
yeah you are right . pointing to the  Github repo reduces the work as well as time.
